from typing import Protocol, Optional, runtime_checkable
from services.user_management.domain.entities import UserProfile, Team
from services.user_management.domain.roles import Role

@runtime_checkable
class UserProfileRepositoryPort(Protocol):
    async def get_by_id(self, user_id: str) -> Optional[UserProfile]: ...
    async def get_by_email(self, email: str) -> Optional[UserProfile]: ...
    async def create(self, profile: UserProfile) -> UserProfile: ...
    async def update(self, profile: UserProfile) -> UserProfile: ...
    async def count_users_by_role(self, role: Role) -> int: ...
    async def list_users(self, page: int, page_size: int, role: Optional[str] = None, team_id: Optional[str] = None) -> list[UserProfile]: ...

@runtime_checkable
class TeamRepositoryPort(Protocol):
    async def get_by_id(self, team_id: str) -> Optional[Team]: ...
    async def create(self, team: Team) -> Team: ...
    async def delete(self, team_id: str) -> None: ...
    async def get_member_count(self, team_id: str) -> int: ...
    async def add_member(self, team_id: str, user_id: str) -> None: ...
    async def remove_member(self, team_id: str, user_id: str) -> None: ...
    async def is_member(self, team_id: str, user_id: str) -> bool: ...
    async def list_members(self, team_id: str) -> list[UserProfile]: ...
