from typing import Protocol, Optional, runtime_checkable
from services.auth.domain.entities import User, BlockedDomain
from services.auth.domain.value_objects import Email

@runtime_checkable
class UserRepositoryPort(Protocol):
    async def get_by_id(self, user_id: str) -> Optional[User]: ...
    async def get_by_email(self, email: Email) -> Optional[User]: ...
    async def create(self, user: User) -> User: ...
    async def get_blocked_domain(self, domain: str) -> Optional[BlockedDomain]: ...

@runtime_checkable
class TokenStorePort(Protocol):
    async def block_refresh_token(self, jti: str, ttl_seconds: int) -> None: ...
    async def is_refresh_token_blocked(self, jti: str) -> bool: ...
    async def record_failed_login(self, email: Email) -> int: ...
    async def get_failed_logins(self, email: Email) -> int: ...
    async def clear_failed_logins(self, email: Email) -> None: ...

@runtime_checkable
class OAuthProviderPort(Protocol):
    async def get_authorization_url(self) -> str: ...
    async def exchange_code_for_user_info(self, code: str) -> dict[str, str]: ...
